source 'https://supermarket.chef.io'

metadata
cookbook "apt"
cookbook "windows"
cookbook "chef_handler", "~> 1.1"
cookbook "yum"
cookbook "bluepill"
cookbook "build-essential"
cookbook  "runit"
cookbook "yum-epel"

