---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[ubuntu]
  - name: centos-6.4
    run_list:
    - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[nginx_simplecgi::default]
    attributes: {
      "nginx_simplecgi": {
        "cgi": true
      }
    }
