name 'chefdk_getting_started'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chefdk_getting_started'
long_description 'Installs/Configures chefdk_getting_started'
version '0.1.0'
